"""Location Scout — picks a new, never-repeated location for each IA
run and tracks every run in an Excel workbook.

Flow (per the user's spec):
  1. Before picking anything, read the Excel tracker and build the set of
     city/state/country combos already used.
  2. Use web search + an LLM call to find a *new* polluted location (river,
     drain, slum, landfill, or polluted lake) anywhere in the target region,
     structured into the same JSON shape the user described:
       {location, country, pollution_type, viral_angle, source_image_query}
     plus the extra fields (area_name, city, state, type) the existing
     frame/clip prompt builders need.
  3. Append a new row to the tracker immediately (status "started") so a
     concurrent/next run never double-picks the same place even before this
     run finishes.
  4. Once the pipeline finishes, ``record_run_result`` goes back and fills in
     the final status + the video link, for tracking.

If web search / the LLM call / the Excel file are unavailable for any reason
(no network, no API key, openpyxl missing, etc.) this degrades gracefully to
the original deterministic rotation file (``ia_locations``), just
skipping any rotation entry whose city/state/country already appears in the
tracker -- the pipeline must never fail to pick *some* location because the
scout step had a problem.
"""

from __future__ import annotations

import json
import logging
import os
import re
import time
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from openjarvis.agents.ia_locations import (
    active_locations,
    location_for_date,
    location_name_pool,
    named_locations,
)
from openjarvis.core.paths import get_config_dir

logger = logging.getLogger(__name__)

_TRACKER_FILENAME = "location_tracker.xlsx"
_COLUMNS = [
    "Date",
    "Run ID",
    "Location",
    "Area Name",
    "City",
    "State",
    "Country",
    "Type",
    "Scene",
    "Pollution Type",
    "Viral Angle",
    "Source Image Query",
    "Status",
    "Video Link",
    # --- Per-platform SEO metadata, appended at the end so older rows /
    # older tracker files stay backward-compatible (see _upgrade_header).
    # Generated by ia_prompts.build_seo_metadata() and written by
    # record_run_result() once a run completes successfully.
    "Instagram Hashtags",
    "Facebook Hashtags",
    "YouTube Title",
    "YouTube Keywords",
    "YouTube Hashtags",
    "TikTok Hashtags",
    "Instagram Caption",
    "Facebook Caption",
    "YouTube Description",
    "TikTok Caption",
    # --- Pinned-comment templates, per 03_SEO_Playbook.md (Rewatch/Rating/
    # Debate trigger for Instagram, vote-for-next-location for Facebook).
    # Appended at the very end so older trackers stay backward-compatible
    # (see _upgrade_header).
    "Instagram Pinned Comment",
    "Facebook Pinned Comment",
]

# (pollution type, label, search-query hint, camera/framing "scene" tag --
# see _CAMERA_STYLES in ia_prompts.py). Rotating through scenes as
# well as pollution types means different runs get visually distinct camera
# treatments (a temple ghat shot across the river, a monument-framed lake,
# a coastline sweep, a bridge-anchored drain) instead of every location
# defaulting to the same locked lengthwise-corridor shot.
_CATEGORIES = [
    ("water", "river or drain", "polluted river or open drain running through a dense urban area", "corridor"),
    ("land", "slum / dumping ground", "trash-strewn slum lane or open dumping ground", "corridor"),
    (
        "water",
        "temple-lined river ghat",
        "polluted river ghat lined with temples and stone steps",
        "ghat",
    ),
    (
        "water",
        "polluted lake or river beside a fort, monument, or heritage structure",
        "polluted urban lake or river running beside a fort, monument, or heritage structure",
        "monument",
    ),
    ("land", "landfill edge", "landfill or waste-dump edge bordering housing", "corridor"),
    (
        "water",
        "polluted coastline or beach",
        "polluted urban coastline, beach, or tidal shore",
        "coast",
    ),
    (
        "water",
        "river or drain crossed by a major bridge or flyover",
        "polluted river or drain crossed by a major bridge, flyover, or rail line",
        "infra",
    ),
]


def _tracker_path(path: Optional[Path] = None) -> Path:
    if path:
        return Path(path)
    return get_config_dir() / "restoration_locations" / _TRACKER_FILENAME


def _norm_key(city: str, state: str, country: str) -> str:
    return f"{(city or '').strip().lower()}|{(state or '').strip().lower()}|{(country or '').strip().lower()}"


def _upgrade_header(ws) -> None:
    """Extend an older tracker's header row with any new trailing columns
    (e.g. the SEO metadata columns added later) so existing trackers/rows
    keep working without losing data -- new columns just read/write blank
    for rows written before they existed."""
    existing = [c.value for c in ws[1]] if ws.max_row >= 1 else []
    for i, col in enumerate(_COLUMNS, start=1):
        if i > len(existing) or existing[i - 1] != col:
            ws.cell(row=1, column=i, value=col)


def _load_workbook(path: Path):
    """Open (or create) the tracker workbook. Returns (workbook, worksheet)."""
    from openpyxl import Workbook, load_workbook

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        wb = load_workbook(path)
        ws = wb.active
        _upgrade_header(ws)
        wb.save(path)
        return wb, ws
    wb = Workbook()
    ws = wb.active
    ws.title = "locations"
    ws.append(_COLUMNS)
    wb.save(path)
    return wb, ws


def _load_used_keys(path: Optional[Path] = None) -> Set[str]:
    """Read every row already in the tracker and return the set of
    city/state/country keys used so far, so the scout never repeats one."""
    tpath = _tracker_path(path)
    if not tpath.exists():
        return set()
    try:
        from openpyxl import load_workbook

        wb = load_workbook(tpath, read_only=True)
        ws = wb.active
        used: Set[str] = set()
        rows = ws.iter_rows(min_row=2, values_only=True)
        for row in rows:
            if not row or len(row) < 7:
                continue
            _, _, _, _, city, state, country = row[:7]
            used.add(_norm_key(city or "", state or "", country or ""))
        return used
    except Exception:
        logger.warning("Could not read location tracker at %s; assuming empty.", tpath, exc_info=True)
        return set()


def _append_row(row: Dict[str, Any], path: Optional[Path] = None) -> None:
    tpath = _tracker_path(path)
    wb, ws = _load_workbook(tpath)
    ws.append([row.get(col, "") for col in _COLUMNS])
    wb.save(tpath)


def record_run_result(
    run_id: str,
    *,
    status: str,
    video_link: str = "",
    seo: Optional[Dict[str, str]] = None,
    path: Optional[Path] = None,
) -> None:
    """Fill in the Status + Video Link columns (and, on success, the
    trailing per-platform SEO columns -- Instagram/Facebook/YouTube/TikTok)
    for *run_id*'s tracker row. *seo* is the dict returned by
    ``ia_prompts.build_seo_metadata()``; keys are matched to
    tracker columns by name so missing keys just leave that cell blank."""
    tpath = _tracker_path(path)
    if not tpath.exists():
        return
    try:
        from openpyxl import load_workbook

        wb = load_workbook(tpath)
        ws = wb.active
        _upgrade_header(ws)
        run_id_col = _COLUMNS.index("Run ID") + 1
        status_col = _COLUMNS.index("Status") + 1
        link_col = _COLUMNS.index("Video Link") + 1
        seo_col_map = {
            "instagram_hashtags": _COLUMNS.index("Instagram Hashtags") + 1,
            "facebook_hashtags": _COLUMNS.index("Facebook Hashtags") + 1,
            "youtube_title": _COLUMNS.index("YouTube Title") + 1,
            "youtube_keywords": _COLUMNS.index("YouTube Keywords") + 1,
            "youtube_hashtags": _COLUMNS.index("YouTube Hashtags") + 1,
            "tiktok_hashtags": _COLUMNS.index("TikTok Hashtags") + 1,
            "instagram_caption": _COLUMNS.index("Instagram Caption") + 1,
            "facebook_caption": _COLUMNS.index("Facebook Caption") + 1,
            "youtube_description": _COLUMNS.index("YouTube Description") + 1,
            "tiktok_caption": _COLUMNS.index("TikTok Caption") + 1,
            "instagram_pinned_comment": _COLUMNS.index("Instagram Pinned Comment") + 1,
            "facebook_pinned_comment": _COLUMNS.index("Facebook Pinned Comment") + 1,
        }
        for row in ws.iter_rows(min_row=2):
            cell = row[run_id_col - 1]
            if cell.value == run_id:
                ws.cell(row=cell.row, column=status_col, value=status)
                if video_link:
                    ws.cell(row=cell.row, column=link_col, value=video_link)
                if seo:
                    for key, col in seo_col_map.items():
                        value = seo.get(key)
                        if value:
                            ws.cell(row=cell.row, column=col, value=value)
                break
        wb.save(tpath)
    except Exception:
        logger.warning("Could not update location tracker for run %s.", run_id, exc_info=True)


def _extract_json(text: str) -> Optional[Dict[str, Any]]:
    """Pull the first {...} JSON object out of an LLM response."""
    if not text:
        return None
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    candidate = fenced.group(1) if fenced else text
    match = re.search(r"\{.*\}", candidate, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def _web_search(query: str) -> str:
    from openjarvis.tools.web_search import WebSearchTool

    result = WebSearchTool().execute(query=query, max_results=5)
    return result.content if result.success else ""


# ---------------------------------------------------------------------------
# Reliability layer for LLM-discovery (added to fix the "every run feels
# generic" complaint -- see the LOCATION_NAME_POOL docstring in
# ia_locations.py for the full root-cause writeup). Two independent
# reliability problems are addressed here, additively, without touching any
# existing timeout value in the codebase:
#   1. Transient failures (a network blip, a rate-limit hiccup) used to cause
#      an immediate, unconditional fallback on the very first try. _retry_llm_call
#      now retries those a couple of times with a short, bounded sleep
#      between attempts -- well under any existing tool timeout.
#   2. Genuine billing/quota-exhausted failures (the OpenAI account itself is
#      out of credits, as happened on a real run) are NOT worth retrying --
#      retrying just burns more wall-clock time for a guaranteed-same result.
#      _is_quota_exhausted_error() detects this case so we fail fast and go
#      straight to the heuristic (no-LLM-call) fallback instead.
# ---------------------------------------------------------------------------
_LLM_MAX_ATTEMPTS = 3


def _is_quota_exhausted_error(exc: BaseException) -> bool:
    """True if *exc* indicates the OpenAI account itself is out of credits or
    has hit its billing hard limit -- a non-transient condition where
    retrying wastes time for no benefit. False for genuinely transient
    errors (rate limiting, timeouts, network blips), which retrying for is
    worthwhile."""
    text = " ".join(
        str(part)
        for part in (getattr(exc, "code", ""), getattr(exc, "message", ""), exc)
        if part
    ).lower()
    return any(
        marker in text
        for marker in (
            "insufficient_quota",
            "exceeded your current quota",
            "billing",
            "hard limit",
            "payment",
        )
    )


def _call_llm_with_retry(fn, *args, **kwargs) -> Optional[Any]:
    """Call *fn* (an OpenAI request) up to ``_LLM_MAX_ATTEMPTS`` times,
    retrying only transient failures with a short bounded backoff and
    failing fast (no retry) on a detected billing/quota-exhausted error.
    Returns ``fn``'s return value, or ``None`` if every attempt failed."""
    for attempt in range(1, _LLM_MAX_ATTEMPTS + 1):
        try:
            return fn(*args, **kwargs)
        except Exception as exc:
            if _is_quota_exhausted_error(exc):
                logger.warning(
                    "Location-scout LLM call hit a billing/quota limit; not retrying.",
                    exc_info=True,
                )
                return None
            if attempt < _LLM_MAX_ATTEMPTS:
                logger.warning(
                    "Location-scout LLM call failed (attempt %d/%d); retrying shortly.",
                    attempt,
                    _LLM_MAX_ATTEMPTS,
                    exc_info=True,
                )
                time.sleep(min(2 ** attempt, 5))
                continue
            logger.warning(
                "Location-scout LLM call failed after %d attempt(s).",
                attempt,
                exc_info=True,
            )
            return None
    return None


def _pool_pick(used_keys: Set[str]) -> Optional[Dict[str, str]]:
    """Return the next not-yet-used entry from
    ``ia_locations.location_name_pool()`` -- the large (100+) real-place
    anchor pool -- or ``None`` once every entry in the pool has been used at
    least once. Pool order is the order the entries are declared in
    ``ia_locations.LOCATION_NAME_POOL``, so distinct regions/cities get
    surfaced in turn rather than the same handful of famous names repeating."""
    for entry in location_name_pool():
        key = _norm_key(entry.get("city", ""), entry.get("state", ""), "India")
        if key not in used_keys:
            return entry
    return None


_HEURISTIC_BEFORE_PHRASES = {
    "water": [
        "dark, polluted water",
        "floating plastic and debris",
        "untreated discharge along the bank",
    ],
    "land": [
        "trash-strewn ground",
        "dilapidated, makeshift structures",
        "open, uncollected dumping",
    ],
}


def _heuristic_enrich_anchor(anchor: Dict[str, str]) -> Dict[str, Any]:
    """Build a non-blank, place-grounded descriptor directly from *anchor*'s
    own name + type, with no LLM/network call at all. This is the
    last-resort path when even the retried LLM-enrichment step fails outright
    (e.g. the OpenAI account hits its billing hard limit, exactly like it did
    on a real run) -- it guarantees ``ia_prompts._location_descriptor()``
    never again receives a fully blank location, because even this
    heuristic text is grounded in the place's own real, specific name rather
    than a generic placeholder."""
    area_name = anchor.get("area_name") or "this location"
    city = anchor.get("city", "")
    state = anchor.get("state", "")
    loc_type = anchor.get("type", "water")
    picked = dict(anchor)
    picked["location"] = f"{area_name}, {city}".strip(", ")
    picked.setdefault("country", "India")
    picked["hero_object"] = area_name
    picked["before"] = list(_HEURISTIC_BEFORE_PHRASES.get(loc_type, _HEURISTIC_BEFORE_PHRASES["water"]))
    picked["camera_notes"] = ""
    picked["pollution_type"] = "pollution and neglect" if loc_type == "land" else "water pollution"
    picked["viral_angle"] = f"{area_name}, {city} gets a second chance"
    picked["source_image_query"] = f"{area_name} {city} {state} pollution aerial".strip()
    return picked


def _llm_enrich_anchor(anchor: Dict[str, str]) -> Optional[Dict[str, Any]]:
    """Ask the LLM to research and describe *anchor* -- a specific, REAL,
    already-named place drawn from ``ia_locations.LOCATION_NAME_POOL`` --
    rather than asking it to invent a brand-new place from scratch each run.
    This is a much more reliable LLM task: the place's existence and
    never-used-ness are already guaranteed by the pool + used_keys dedup
    check, so the LLM only has to describe something concrete (hero_object,
    before/condition, camera notes, pollution type, viral angle), which is
    far less failure-prone than "invent and verify a brand-new place in one
    shot". Retries transient failures via ``_call_llm_with_retry``; returns
    ``None`` (never raises) if every attempt fails, including a fast-fail
    on a detected billing/quota-exhausted error."""
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    try:
        import openai
    except ImportError:
        return None

    area_name = anchor.get("area_name", "")
    city = anchor.get("city", "")
    state = anchor.get("state", "")
    loc_type = anchor.get("type", "water")

    try:
        search_context = _web_search(f"{area_name} {city} pollution restoration aerial 2026")
    except Exception:
        logger.warning(
            "Web-search step failed for anchor '%s, %s'; continuing with LLM knowledge only.",
            area_name,
            city,
            exc_info=True,
        )
        search_context = ""

    system = (
        "You research real, specific, named polluted locations in India for"
        " a restoration-reel video series. You must answer with ONLY a"
        " single JSON object, no prose, no markdown fences."
    )
    user_prompt = (
        "Describe this REAL, specific place for a viral pollution-to-"
        f"restoration drone reel: '{area_name}, {city}, {state}, India'"
        f" (type: {loc_type}).\n\n"
        "Background search context (may be partial/noisy, use what's useful,"
        f" ignore the rest):\n{search_context[:3000]}\n\n"
        "Respond with ONLY this JSON shape (no extra keys, no commentary):\n"
        "{\n"
        '  "hero_object": "<the specific physical thing the camera should focus on>",\n'
        '  "before": ["<short phrase>", "<short phrase>", "<short phrase>"],\n'
        '  "camera_notes": "<short camera framing note specific to this place>",\n'
        '  "pollution_type": "<short description, e.g. \'black water + plastic\'>",\n'
        '  "viral_angle": "<one punchy sentence pitching why this is shareable>",\n'
        '  "source_image_query": "<a good image-search query for this place>"\n'
        "}"
    )

    def _call() -> Dict[str, Any]:
        client = openai.OpenAI()
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.7,
        )
        text = response.choices[0].message.content or ""
        data = _extract_json(text)
        if not data:
            raise ValueError("Location-scout LLM enrichment did not return parsable JSON.")
        return data

    data = _call_llm_with_retry(_call)
    if not data:
        return None

    picked = dict(anchor)
    picked["location"] = f"{area_name}, {city}".strip(", ")
    picked.setdefault("country", "India")
    picked["hero_object"] = data.get("hero_object", "") or area_name
    before = data.get("before")
    picked["before"] = before if isinstance(before, list) and before else list(
        _HEURISTIC_BEFORE_PHRASES.get(loc_type, _HEURISTIC_BEFORE_PHRASES["water"])
    )
    picked["camera_notes"] = data.get("camera_notes", "")
    picked["pollution_type"] = data.get("pollution_type", "") or (
        "pollution and neglect" if loc_type == "land" else "water pollution"
    )
    picked["viral_angle"] = data.get("viral_angle", "") or f"{area_name}, {city} gets a second chance"
    picked["source_image_query"] = data.get("source_image_query") or f"{area_name} {city} pollution aerial"
    return picked


def _llm_pick_location(
    region: str,
    used_keys: Set[str],
    search_context: str,
    category_type: str,
    category_label: str,
    category_scene: str = "corridor",
) -> Optional[Dict[str, Any]]:
    """Ask an LLM to turn search context into a structured, never-used pick."""
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    try:
        import openai
    except ImportError:
        return None

    used_list = "\n".join(f"- {k}" for k in sorted(used_keys)) or "(none yet)"
    region_label = "India" if region == "india" else "anywhere internationally"
    system = (
        "You select real, specific, named locations for a restoration-reel"
        " video series. You must answer with ONLY a single JSON object, no"
        " prose, no markdown fences."
    )
    user_prompt = (
        f"Pick ONE new, real, specific {category_label} location"
        f" ({region_label}) suitable for a viral pollution-to-restoration"
        " drone reel. It must be a real, named place (city + specific"
        " river/drain/slum/lake/landfill name), and it must NOT match any of"
        " these already-used city|state|country combos (case-insensitive):\n"
        f"{used_list}\n\n"
        "Background search context (may be partial/noisy, use what's useful,"
        f" ignore the rest):\n{search_context[:3000]}\n\n"
        "Respond with ONLY this JSON shape (no extra keys, no commentary):\n"
        "{\n"
        '  "location": "<short display name, e.g. \'Najafgarh Drain, Delhi\'>",\n'
        '  "area_name": "<the specific river/drain/slum/lake/landfill name>",\n'
        '  "city": "<city>",\n'
        '  "state": "<state/province, empty string if not applicable>",\n'
        '  "country": "<country>",\n'
        f'  "type": "{category_type}",\n'
        f'  "scene": "{category_scene}",\n'
        '  "pollution_type": "<short description, e.g. \'water + waste\'>",\n'
        '  "viral_angle": "<one punchy sentence pitching why this is shareable>",\n'
        '  "source_image_query": "<a good image-search query for this place>"\n'
        "}"
    )
    try:
        client = openai.OpenAI()
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.7,
        )
        text = response.choices[0].message.content or ""
    except Exception:
        logger.warning("Location-scout LLM call failed.", exc_info=True)
        return None

    data = _extract_json(text)
    if not data:
        return None
    required = ("location", "area_name", "city", "country", "type", "pollution_type", "viral_angle", "source_image_query")
    if not all(k in data for k in required):
        return None
    data.setdefault("state", "")
    data.setdefault("scene", category_scene)
    key = _norm_key(data.get("city", ""), data.get("state", ""), data.get("country", ""))
    if key in used_keys:
        return None
    return data


def _fallback_rotation_pick(region: str, used_keys: Set[str]) -> Dict[str, Any]:
    """Last-resort pick from the static rotation file, skipping anything
    already in the tracker. Falls back to the deterministic date-based pick
    (allowing a repeat) only once every rotation entry has been used."""
    locations = active_locations(region=region)
    for loc in locations:
        country = "India" if region == "india" else loc.get("country", "")
        key = _norm_key(loc.get("city", ""), loc.get("state", ""), country)
        if key not in used_keys:
            picked = dict(loc)
            picked.setdefault("country", country)
            picked.setdefault("scene", "corridor")
            picked.setdefault("pollution_type", "")
            picked.setdefault("viral_angle", "")
            picked.setdefault("source_image_query", f"{loc.get('area_name', '')} {loc.get('city', '')} pollution aerial")
            picked["location"] = f"{loc.get('area_name', '')}, {loc.get('city', '')}".strip(", ")
            return picked
    # Every rotation entry already used at least once -- fall back to the
    # original deterministic date rotation so the pipeline still runs.
    loc = location_for_date(region=region)
    picked = dict(loc)
    country = "India" if region == "india" else loc.get("country", "")
    picked.setdefault("country", country)
    picked.setdefault("scene", "corridor")
    picked.setdefault("pollution_type", "")
    picked.setdefault("viral_angle", "")
    picked.setdefault("source_image_query", f"{loc.get('area_name', '')} {loc.get('city', '')} pollution aerial")
    picked["location"] = f"{loc.get('area_name', '')}, {loc.get('city', '')}".strip(", ")
    return picked


def _named_kb_pick(used_keys: Set[str]) -> Optional[Dict[str, Any]]:
    """Try the curated Location Knowledge Base first (04_Location_Knowledge_
    Base.md, see ``ia_locations.named_locations()``), highest viral score
    not yet used. Returns None once every curated entry has been used at
    least once, so callers fall through to the existing LLM/web-search step
    -- this is a pure priority layer added in front of the old pipeline, the
    old pipeline itself is untouched."""
    for loc in named_locations(sort_by_viral_score=True):
        key = _norm_key(loc.get("city", ""), loc.get("state", ""), loc.get("country", ""))
        if key not in used_keys:
            return dict(loc)
    return None


def scout_location(
    *,
    region: str = "india",
    run_id: str,
    tracker_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Pick a fresh, never-repeated location and log it to the Excel
    tracker immediately (status "started"). Returns a location dict shaped
    for ``build_frame_prompts``/``build_clip_prompts`` (needs at least
    ``id``, ``area_name``, ``city``, ``type``), plus the extra scouting
    fields (state, country, pollution_type, viral_angle,
    source_image_query) for the tracker/record.
    """
    used_keys = _load_used_keys(tracker_path)

    day_index = date.today().toordinal()
    category_type, category_label, category_query_hint, category_scene = _CATEGORIES[
        day_index % len(_CATEGORIES)
    ]

    # Step 0a: the user's own curated, hand-picked Location Knowledge Base
    # (04_Location_Knowledge_Base.md) takes priority over the generic
    # LLM/web-search step -- these 7 locations are pre-vetted with their own
    # Hero Object / Emotional Trigger / Restoration Concept / viral score,
    # so use them (highest viral score, not yet used) before inventing a new
    # one. Falls through to the existing LLM/web-search step once all 7 have
    # been used at least once.
    picked: Optional[Dict[str, Any]] = _named_kb_pick(used_keys)
    if picked is not None:
        picked.setdefault("scene", category_scene)
        try:
            _append_row(
                {
                    "Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "Run ID": run_id,
                    "Location": picked.get("location", ""),
                    "Area Name": picked.get("area_name", ""),
                    "City": picked.get("city", ""),
                    "State": picked.get("state", ""),
                    "Country": picked.get("country", ""),
                    "Type": picked.get("type", ""),
                    "Scene": picked.get("scene", "corridor"),
                    "Pollution Type": picked.get("pollution_type", ""),
                    "Viral Angle": picked.get("viral_angle", ""),
                    "Source Image Query": picked.get("source_image_query", ""),
                    "Status": "started",
                    "Video Link": "",
                },
                tracker_path,
            )
        except Exception:
            logger.warning("Could not write location-scout row to tracker.", exc_info=True)
        return picked

    # Step 0b: anchor-and-enrich against the large (100+) real-place name
    # pool (ia_locations.LOCATION_NAME_POOL) -- this is now the PRIMARY
    # location-discovery engine per the user's directive to make
    # LLM-discovery reliable and always surface a new/different real place,
    # rather than relying on the small curated KB or the bare rotation file.
    # The pool guarantees the place is real and never-used; the LLM is only
    # asked to describe/research it (with retry-with-backoff for transient
    # failures, fail-fast for billing/quota errors), which is far more
    # reliable than the old "invent a brand-new place from scratch" prompt.
    # Even if the LLM step fails outright, the heuristic fallback below still
    # grounds the descriptor in the pool entry's own real name, so
    # ia_prompts._location_descriptor() never again sees a blank location.
    anchor = _pool_pick(used_keys)
    if anchor is not None:
        picked = _llm_enrich_anchor(anchor)
        if picked is None:
            picked = _heuristic_enrich_anchor(anchor)
        picked.setdefault("id", re.sub(r"[^a-z0-9]+", "_", picked.get("location", "location").lower()).strip("_"))
        picked.setdefault("country", "India")
        picked.setdefault("scene", category_scene)
        try:
            _append_row(
                {
                    "Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                    "Run ID": run_id,
                    "Location": picked.get("location", ""),
                    "Area Name": picked.get("area_name", ""),
                    "City": picked.get("city", ""),
                    "State": picked.get("state", ""),
                    "Country": picked.get("country", ""),
                    "Type": picked.get("type", ""),
                    "Scene": picked.get("scene", "corridor"),
                    "Pollution Type": picked.get("pollution_type", ""),
                    "Viral Angle": picked.get("viral_angle", ""),
                    "Source Image Query": picked.get("source_image_query", ""),
                    "Status": "started",
                    "Video Link": "",
                },
                tracker_path,
            )
        except Exception:
            logger.warning("Could not write location-scout row to tracker.", exc_info=True)
        return picked

    # Step 0c (extremely unlikely in practice -- the pool above has 80+
    # entries -- but kept as a safety net): every pool entry has been used
    # at least once, so fall through to the older free-text "invent a new
    # place" LLM step, then the bare rotation file as the final safety net.
    # Neither of these older paths is removed; they just become unreachable
    # until the pool itself is exhausted.
    try:
        search_query = (
            f"{category_query_hint} in "
            f"{'India' if region == 'india' else 'a major city'} 2026 viral aerial drone"
        )
        search_context = _web_search(search_query)
        picked = _llm_pick_location(
            region, used_keys, search_context, category_type, category_label, category_scene
        )
    except Exception:
        logger.warning("Location scout web-search/LLM step failed; falling back.", exc_info=True)
        picked = None

    if picked is None:
        # NOTE: do NOT stamp the day's rotated category_scene onto a
        # fallback-picked location -- the rotation's scene (e.g. "monument")
        # is only valid for whatever real place the LLM/web-search step
        # actually found and verified for that category. A static rotation
        # entry was never vetted against that category, so forcing it here
        # previously caused locations with no real adjacent monument (e.g.
        # Mithi River banks, Mumbai; Najafgarh Drain, Delhi) to be tagged
        # "monument" purely because that's what day-of-year % len(_CATEGORIES)
        # happened to land on -- which then led the image-gen step to
        # fabricate/imply a heritage structure (in practice, Gateway of
        # India, Mumbai's most famous one) that doesn't actually exist
        # there. _fallback_rotation_pick already supplies its own safe,
        # generic default ("corridor") when the entry has no scene of its
        # own.
        picked = _fallback_rotation_pick(region, used_keys)

    picked.setdefault("id", re.sub(r"[^a-z0-9]+", "_", picked.get("location", "location").lower()).strip("_"))
    picked.setdefault("country", "India" if region == "india" else "")
    picked.setdefault("scene", category_scene)

    try:
        _append_row(
            {
                "Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "Run ID": run_id,
                "Location": picked.get("location", ""),
                "Area Name": picked.get("area_name", ""),
                "City": picked.get("city", ""),
                "State": picked.get("state", ""),
                "Country": picked.get("country", ""),
                "Type": picked.get("type", ""),
                "Scene": picked.get("scene", "corridor"),
                "Pollution Type": picked.get("pollution_type", ""),
                "Viral Angle": picked.get("viral_angle", ""),
                "Source Image Query": picked.get("source_image_query", ""),
                "Status": "started",
                "Video Link": "",
            },
            tracker_path,
        )
    except Exception:
        logger.warning("Could not write location-scout row to tracker.", exc_info=True)

    return picked


__all__ = [
    "scout_location",
    "record_run_result",
    "_pool_pick",
    "_llm_enrich_anchor",
    "_heuristic_enrich_anchor",
    "_call_llm_with_retry",
    "_is_quota_exhausted_error",
]
