"""Location Scout — picks a new, never-repeated location for each Punarnirman
run and tracks every run in an Excel workbook.

Flow (per the user's spec):
  1. Before picking anything, read the Excel tracker and build the set of
     city/state/country combos already used.
  2. Use web search + an LLM call to find a *new* polluted location (river,
     drain, slum, landfill, or polluted lake) anywhere in the target region,
     structured into the same JSON shape the user described:
       {location, country, pollution_type, viral_angle, source_image_query}
     plus the extra fields (area_name, city, state, type) the existing
     frame/clip prompt builders need.
  3. Append a new row to the tracker immediately (status "started") so a
     concurrent/next run never double-picks the same place even before this
     run finishes.
  4. Once the pipeline finishes, ``record_run_result`` goes back and fills in
     the final status + the video link, for tracking.

If web search / the LLM call / the Excel file are unavailable for any reason
(no network, no API key, openpyxl missing, etc.) this degrades gracefully to
the original deterministic rotation file (``punarnirman_locations``), just
skipping any rotation entry whose city/state/country already appears in the
tracker -- the pipeline must never fail to pick *some* location because the
scout step had a problem.
"""

from __future__ import annotations

import json
import logging
import os
import re
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from openjarvis.agents.punarnirman_locations import active_locations, location_for_date
from openjarvis.core.paths import get_config_dir

logger = logging.getLogger(__name__)

_TRACKER_FILENAME = "location_tracker.xlsx"
_COLUMNS = [
    "Date",
    "Run ID",
    "Location",
    "Area Name",
    "City",
    "State",
    "Country",
    "Type",
    "Scene",
    "Pollution Type",
    "Viral Angle",
    "Source Image Query",
    "Status",
    "Video Link",
    # --- Per-platform SEO metadata, appended at the end so older rows /
    # older tracker files stay backward-compatible (see _upgrade_header).
    # Generated by punarnirman_prompts.build_seo_metadata() and written by
    # record_run_result() once a run completes successfully.
    "Instagram Hashtags",
    "Facebook Hashtags",
    "YouTube Title",
    "YouTube Keywords",
    "YouTube Hashtags",
    "TikTok Hashtags",
    "Instagram Caption",
    "Facebook Caption",
    "YouTube Description",
    "TikTok Caption",
]

# (pollution type, label, search-query hint, camera/framing "scene" tag --
# see _CAMERA_STYLES in punarnirman_prompts.py). Rotating through scenes as
# well as pollution types means different runs get visually distinct camera
# treatments (a temple ghat shot across the river, a monument-framed lake,
# a coastline sweep, a bridge-anchored drain) instead of every location
# defaulting to the same locked lengthwise-corridor shot.
_CATEGORIES = [
    ("water", "river or drain", "polluted river or open drain running through a dense urban area", "corridor"),
    ("land", "slum / dumping ground", "trash-strewn slum lane or open dumping ground", "corridor"),
    (
        "water",
        "temple-lined river ghat",
        "polluted river ghat lined with temples and stone steps",
        "ghat",
    ),
    (
        "water",
        "polluted lake or river beside a fort, monument, or heritage structure",
        "polluted urban lake or river running beside a fort, monument, or heritage structure",
        "monument",
    ),
    ("land", "landfill edge", "landfill or waste-dump edge bordering housing", "corridor"),
    (
        "water",
        "polluted coastline or beach",
        "polluted urban coastline, beach, or tidal shore",
        "coast",
    ),
    (
        "water",
        "river or drain crossed by a major bridge or flyover",
        "polluted river or drain crossed by a major bridge, flyover, or rail line",
        "infra",
    ),
]


def _tracker_path(path: Optional[Path] = None) -> Path:
    if path:
        return Path(path)
    return get_config_dir() / "restoration_locations" / _TRACKER_FILENAME


def _norm_key(city: str, state: str, country: str) -> str:
    return f"{(city or '').strip().lower()}|{(state or '').strip().lower()}|{(country or '').strip().lower()}"


def _upgrade_header(ws) -> None:
    """Extend an older tracker's header row with any new trailing columns
    (e.g. the SEO metadata columns added later) so existing trackers/rows
    keep working without losing data -- new columns just read/write blank
    for rows written before they existed."""
    existing = [c.value for c in ws[1]] if ws.max_row >= 1 else []
    for i, col in enumerate(_COLUMNS, start=1):
        if i > len(existing) or existing[i - 1] != col:
            ws.cell(row=1, column=i, value=col)


def _load_workbook(path: Path):
    """Open (or create) the tracker workbook. Returns (workbook, worksheet)."""
    from openpyxl import Workbook, load_workbook

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        wb = load_workbook(path)
        ws = wb.active
        _upgrade_header(ws)
        wb.save(path)
        return wb, ws
    wb = Workbook()
    ws = wb.active
    ws.title = "locations"
    ws.append(_COLUMNS)
    wb.save(path)
    return wb, ws


def _load_used_keys(path: Optional[Path] = None) -> Set[str]:
    """Read every row already in the tracker and return the set of
    city/state/country keys used so far, so the scout never repeats one."""
    tpath = _tracker_path(path)
    if not tpath.exists():
        return set()
    try:
        from openpyxl import load_workbook

        wb = load_workbook(tpath, read_only=True)
        ws = wb.active
        used: Set[str] = set()
        rows = ws.iter_rows(min_row=2, values_only=True)
        for row in rows:
            if not row or len(row) < 7:
                continue
            _, _, _, _, city, state, country = row[:7]
            used.add(_norm_key(city or "", state or "", country or ""))
        return used
    except Exception:
        logger.warning("Could not read location tracker at %s; assuming empty.", tpath, exc_info=True)
        return set()


def _append_row(row: Dict[str, Any], path: Optional[Path] = None) -> None:
    tpath = _tracker_path(path)
    wb, ws = _load_workbook(tpath)
    ws.append([row.get(col, "") for col in _COLUMNS])
    wb.save(tpath)


def record_run_result(
    run_id: str,
    *,
    status: str,
    video_link: str = "",
    seo: Optional[Dict[str, str]] = None,
    path: Optional[Path] = None,
) -> None:
    """Fill in the Status + Video Link columns (and, on success, the
    trailing per-platform SEO columns -- Instagram/Facebook/YouTube/TikTok)
    for *run_id*'s tracker row. *seo* is the dict returned by
    ``punarnirman_prompts.build_seo_metadata()``; keys are matched to
    tracker columns by name so missing keys just leave that cell blank."""
    tpath = _tracker_path(path)
    if not tpath.exists():
        return
    try:
        from openpyxl import load_workbook

        wb = load_workbook(tpath)
        ws = wb.active
        _upgrade_header(ws)
        run_id_col = _COLUMNS.index("Run ID") + 1
        status_col = _COLUMNS.index("Status") + 1
        link_col = _COLUMNS.index("Video Link") + 1
        seo_col_map = {
            "instagram_hashtags": _COLUMNS.index("Instagram Hashtags") + 1,
            "facebook_hashtags": _COLUMNS.index("Facebook Hashtags") + 1,
            "youtube_title": _COLUMNS.index("YouTube Title") + 1,
            "youtube_keywords": _COLUMNS.index("YouTube Keywords") + 1,
            "youtube_hashtags": _COLUMNS.index("YouTube Hashtags") + 1,
            "tiktok_hashtags": _COLUMNS.index("TikTok Hashtags") + 1,
            "instagram_caption": _COLUMNS.index("Instagram Caption") + 1,
            "facebook_caption": _COLUMNS.index("Facebook Caption") + 1,
            "youtube_description": _COLUMNS.index("YouTube Description") + 1,
            "tiktok_caption": _COLUMNS.index("TikTok Caption") + 1,
        }
        for row in ws.iter_rows(min_row=2):
            cell = row[run_id_col - 1]
            if cell.value == run_id:
                ws.cell(row=cell.row, column=status_col, value=status)
                if video_link:
                    ws.cell(row=cell.row, column=link_col, value=video_link)
                if seo:
                    for key, col in seo_col_map.items():
                        value = seo.get(key)
                        if value:
                            ws.cell(row=cell.row, column=col, value=value)
                break
        wb.save(tpath)
    except Exception:
        logger.warning("Could not update location tracker for run %s.", run_id, exc_info=True)


def _extract_json(text: str) -> Optional[Dict[str, Any]]:
    """Pull the first {...} JSON object out of an LLM response."""
    if not text:
        return None
    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    candidate = fenced.group(1) if fenced else text
    match = re.search(r"\{.*\}", candidate, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def _web_search(query: str) -> str:
    from openjarvis.tools.web_search import WebSearchTool

    result = WebSearchTool().execute(query=query, max_results=5)
    return result.content if result.success else ""


def _llm_pick_location(
    region: str,
    used_keys: Set[str],
    search_context: str,
    category_type: str,
    category_label: str,
    category_scene: str = "corridor",
) -> Optional[Dict[str, Any]]:
    """Ask an LLM to turn search context into a structured, never-used pick."""
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    try:
        import openai
    except ImportError:
        return None

    used_list = "\n".join(f"- {k}" for k in sorted(used_keys)) or "(none yet)"
    region_label = "India" if region == "india" else "anywhere internationally"
    system = (
        "You select real, specific, named locations for a restoration-reel"
        " video series. You must answer with ONLY a single JSON object, no"
        " prose, no markdown fences."
    )
    user_prompt = (
        f"Pick ONE new, real, specific {category_label} location"
        f" ({region_label}) suitable for a viral pollution-to-restoration"
        " drone reel. It must be a real, named place (city + specific"
        " river/drain/slum/lake/landfill name), and it must NOT match any of"
        " these already-used city|state|country combos (case-insensitive):\n"
        f"{used_list}\n\n"
        "Background search context (may be partial/noisy, use what's useful,"
        f" ignore the rest):\n{search_context[:3000]}\n\n"
        "Respond with ONLY this JSON shape (no extra keys, no commentary):\n"
        "{\n"
        '  "location": "<short display name, e.g. \'Najafgarh Drain, Delhi\'>",\n'
        '  "area_name": "<the specific river/drain/slum/lake/landfill name>",\n'
        '  "city": "<city>",\n'
        '  "state": "<state/province, empty string if not applicable>",\n'
        '  "country": "<country>",\n'
        f'  "type": "{category_type}",\n'
        f'  "scene": "{category_scene}",\n'
        '  "pollution_type": "<short description, e.g. \'water + waste\'>",\n'
        '  "viral_angle": "<one punchy sentence pitching why this is shareable>",\n'
        '  "source_image_query": "<a good image-search query for this place>"\n'
        "}"
    )
    try:
        client = openai.OpenAI()
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.7,
        )
        text = response.choices[0].message.content or ""
    except Exception:
        logger.warning("Location-scout LLM call failed.", exc_info=True)
        return None

    data = _extract_json(text)
    if not data:
        return None
    required = ("location", "area_name", "city", "country", "type", "pollution_type", "viral_angle", "source_image_query")
    if not all(k in data for k in required):
        return None
    data.setdefault("state", "")
    data.setdefault("scene", category_scene)
    key = _norm_key(data.get("city", ""), data.get("state", ""), data.get("country", ""))
    if key in used_keys:
        return None
    return data


def _fallback_rotation_pick(region: str, used_keys: Set[str]) -> Dict[str, Any]:
    """Last-resort pick from the static rotation file, skipping anything
    already in the tracker. Falls back to the deterministic date-based pick
    (allowing a repeat) only once every rotation entry has been used."""
    locations = active_locations(region=region)
    for loc in locations:
        country = "India" if region == "india" else loc.get("country", "")
        key = _norm_key(loc.get("city", ""), loc.get("state", ""), country)
        if key not in used_keys:
            picked = dict(loc)
            picked.setdefault("country", country)
            picked.setdefault("scene", "corridor")
            picked.setdefault("pollution_type", "")
            picked.setdefault("viral_angle", "")
            picked.setdefault("source_image_query", f"{loc.get('area_name', '')} {loc.get('city', '')} pollution aerial")
            picked["location"] = f"{loc.get('area_name', '')}, {loc.get('city', '')}".strip(", ")
            return picked
    # Every rotation entry already used at least once -- fall back to the
    # original deterministic date rotation so the pipeline still runs.
    loc = location_for_date(region=region)
    picked = dict(loc)
    country = "India" if region == "india" else loc.get("country", "")
    picked.setdefault("country", country)
    picked.setdefault("scene", "corridor")
    picked.setdefault("pollution_type", "")
    picked.setdefault("viral_angle", "")
    picked.setdefault("source_image_query", f"{loc.get('area_name', '')} {loc.get('city', '')} pollution aerial")
    picked["location"] = f"{loc.get('area_name', '')}, {loc.get('city', '')}".strip(", ")
    return picked


def scout_location(
    *,
    region: str = "india",
    run_id: str,
    tracker_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Pick a fresh, never-repeated location and log it to the Excel
    tracker immediately (status "started"). Returns a location dict shaped
    for ``build_frame_prompts``/``build_clip_prompts`` (needs at least
    ``id``, ``area_name``, ``city``, ``type``), plus the extra scouting
    fields (state, country, pollution_type, viral_angle,
    source_image_query) for the tracker/record.
    """
    used_keys = _load_used_keys(tracker_path)

    day_index = date.today().toordinal()
    category_type, category_label, category_query_hint, category_scene = _CATEGORIES[
        day_index % len(_CATEGORIES)
    ]

    picked: Optional[Dict[str, Any]] = None
    try:
        search_query = (
            f"{category_query_hint} in "
            f"{'India' if region == 'india' else 'a major city'} 2026 viral aerial drone"
        )
        search_context = _web_search(search_query)
        picked = _llm_pick_location(
            region, used_keys, search_context, category_type, category_label, category_scene
        )
    except Exception:
        logger.warning("Location scout web-search/LLM step failed; falling back.", exc_info=True)
        picked = None

    if picked is None:
        # NOTE: do NOT stamp the day's rotated category_scene onto a
        # fallback-picked location -- the rotation's scene (e.g. "monument")
        # is only valid for whatever real place the LLM/web-search step
        # actually found and verified for that category. A static rotation
        # entry was never vetted against that category, so forcing it here
        # previously caused locations with no real adjacent monument (e.g.
        # Mithi River banks, Mumbai; Najafgarh Drain, Delhi) to be tagged
        # "monument" purely because that's what day-of-year % len(_CATEGORIES)
        # happened to land on -- which then led the image-gen step to
        # fabricate/imply a heritage structure (in practice, Gateway of
        # India, Mumbai's most famous one) that doesn't actually exist
        # there. _fallback_rotation_pick already supplies its own safe,
        # generic default ("corridor") when the entry has no scene of its
        # own.
        picked = _fallback_rotation_pick(region, used_keys)

    picked.setdefault("id", re.sub(r"[^a-z0-9]+", "_", picked.get("location", "location").lower()).strip("_"))
    picked.setdefault("country", "India" if region == "india" else "")
    picked.setdefault("scene", category_scene)

    try:
        _append_row(
            {
                "Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "Run ID": run_id,
                "Location": picked.get("location", ""),
                "Area Name": picked.get("area_name", ""),
                "City": picked.get("city", ""),
                "State": picked.get("state", ""),
                "Country": picked.get("country", ""),
                "Type": picked.get("type", ""),
                "Scene": picked.get("scene", "corridor"),
                "Pollution Type": picked.get("pollution_type", ""),
                "Viral Angle": picked.get("viral_angle", ""),
                "Source Image Query": picked.get("source_image_query", ""),
                "Status": "started",
                "Video Link": "",
            },
            tracker_path,
        )
    except Exception:
        logger.warning("Could not write location-scout row to tracker.", exc_info=True)

    return picked


__all__ = ["scout_location", "record_run_result"]
